name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: [self-hosted, docker, internet]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Run Coverage
      run: |
        make test
        make check-coverage
